server:
  port: 9090

spring:
  application:
    name: gateway_demo
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8088/auth/realms/master
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: spring-cloud-gateway-client
            client-secret: bf89e0ef-004d-4865-b840-7170273ffac3

  cloud:
    gateway:
      default-filters:
        - TokenRelay

      routes:
        - id: httpbin
          uri: https://httpbin.org
          predicates:
            - Path=/httpbin/**
          filters:
            - StripPrefix=1

        - id: flights-service
          uri: http://localhost:8090
          predicates:
            - Path=/openfhir_api_war_exploded/**

logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG